### ISSUE TITLE
Email Validator as a sensible default

### ISSUE THREAD

**Issue by ersin-ertan** [daniel-martins-IR/Blorm#1]
Nice lib.

Regex is a possible solution.
Apache Commons Validator is another(but then a dependency).
https://java.net/projects/javamail/pages/Android for Java lang solution specific to android.
https://tools.ietf.org/html/rfc2822 RFC compliance considerations.

My use case is for mobile login via email address, so it will mostly be as(and what I consider to be standard enough):
`someName   @   companyDomain   .   topLevelInternetDomain`

**Comment by bloderxd** [comment]
@ersin-ertan looks like a good validation, I'm going to implement it.

**Comment by bloderxd** [comment]
@ersin-ertan Thank you to suggest it, now you can check if that field has an email with:

``` java
new Blorm.Builder().field(editText).is(email)
```

and you can pass a custom error message to this validation:

``` java
new Blorm.Builder().field(editText).is("Sorry, put a valid email, please", email)
```

check it, and close this issue please.

**Comment by ersin-ertan** [comment]
This code is generating unexpected functionality, the username and(...) message in not being displayed, instead the default for email "invalid email address" is being displayed.
Invalid username is appearing for the password edittext instead of the username one.

``` java
    new Blorm.Builder().field(username)
        .is(filled)
        .and(getString(R.string.invalid_username), email)
        .andField(password)
        .is(getString(R.string.invalid_password), filled)
        .onSuccess(() -> {
          Utils.toast(this, R.string.logging_in);
        })
        .submitOn(btnLogin);
```

I would also expect that I get two different error messages based on which of the input validations are triggering. Ex. No input, and invalid input for filled and email respectively.

**Comment by bloderxd** [comment]
Ok, thank you to report it, I will fix it.
