### ISSUE TITLE
Error to bubble to populate multi views

### ISSUE THREAD

**Issue by ersin-ertan** [daniel-martins-IR/Blorm#3]
When validating multiple views in one Blorm, I have tried .is(errorMessage, filled) with all of the views. But currently only the field(view) will get the error image and text on button press. If this is working as intended, then I request the feature to toggle the error image and text to fields passed in. 
`.errorAllViews()`

**Comment by bloderxd** [comment]
Apparently I fixed this issue, check it and close this issue, please.
