### ISSUE TITLE
Version 2.2 does not include filled changes

### ISSUE THREAD

**Issue by ersin-ertan** [daniel-martins-IR/Blorm#7]
The latest release doesn't have filled changes, and the github badge is still at 2.1

**Comment by bloderxd** [comment]
I'm gonna change it.

**Comment by bloderxd** [comment]
Ok, sorry about it, I'm little out of time but, I already post your modifications, then check it and close this issue please. And I don't know why github badge shows one version before, but your modification has already been posted.
